### ISSUE TITLE
Need to change the admin dashboard

### ISSUE THREAD

**Issue by puneet739** [puneet739/SocietyFocus-Portal#16]
Hi , 

we have a portal and need to change our admin dashboard. The board should be of this format. 
It should be integrated with backend services and display a board of changes. 
The change should be as displayed in image attached. 

Let me know if it is feasible for you. 

Its only small Admin Dashboard. with 6 small widgets. API will be provided. 

![admindashboard](https://cloud.githubusercontent.com/assets/4660008/26599734/3c7b6f40-4597-11e7-8822-3f10347d7f4b.PNG)

**Comment by puneet739** [comment]
API for complaints. 
/service/v1/complaint/data


API for Society Expenses
/service/society/incomeexpense

**Comment by puneet739** [comment]
there will be 2 graphs. 

And 7 Below boxes will be just placeholder and on clicking them redirect to different page.

**Comment by puneet739** [comment]
Admin credentials for live website
URL :: http://societyfocus.com/portal/
Username : anil@gmail.com
Password : 123456
Society :: Srs Residency Demo

**Comment by it-sumanp** [comment]
I can help you on this

**Comment by pankajladhar** [comment]
I can help you on this. We can connect on 9731203535.

**Comment by puneet739** [comment]
@it-sumanp  Kindly connect with me over 9711616135, Kindly suggest by when can i expect this to be completed.

**Comment by puneet739** [comment]
For charting we should use http://www.chartjs.org with basic animations. 

http://www.chartjs.org/docs/latest/configuration/animations.html

**Comment by puneet739** [comment]
Fixed and closed. Thanks @Shivamdube96
